USE [homeMaintenance]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

   CREATE TABLE dbo.UserPayment
	(
		Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY NOT NULL,
		UserId UNIQUEIDENTIFIER NOT NULL,
		EmployeeId UNIQUEIDENTIFIER NOT NULL,
		PaymentId VARCHAR(MAX) NOT NULL,
		PaymentCreatedAt DATETIME DEFAULT GETDATE() NOT NULL,
		StartDateTime DATETIME NOT NULL,
		EndDateTime DATETIME NOT NULL,
		Amount BIGINT NOT NULL,

	
		CONSTRAINT FK_UserPayment_User FOREIGN KEY (UserId) REFERENCES dbo.Users(Id),
		CONSTRAINT FK_UserPayment_Employee FOREIGN KEY (EmployeeId) REFERENCES dbo.Users(Id)
	);
