BEGIN TRANSACTION;

COMMIT;
GO 

ALTER TABLE dbo.UserImages
ADD UserId UNIQUEIDENTIFIER;

ALTER TABLE dbo.UserImages
ADD CONSTRAINT FK_UserImages_Users
FOREIGN KEY (UserId) REFERENCES Users(Id);

GO;
