CREATE TABLE dbo.UserPayment
	(
		Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY NOT NULL,
		UserId UNIQUEIDENTIFIER NOT NULL,
		EmployeeId UNIQUEIDENTIFIER NOT NULL,
		PaymentId VARCHAR(MAX) NULL,
		PaymentCreatedAt DATETIME DEFAULT GETDATE() NOT NULL,
		StartDateTime DATETIME NOT NULL,
		EndDateTime DATETIME NOT NULL,
		Amount BIGINT NOT NULL,

	
		CONSTRAINT FK_UserPayment_User FOREIGN KEY (UserId) REFERENCES dbo.Users(Id),
		CONSTRAINT FK_UserPayment_Employee FOREIGN KEY (EmployeeId) REFERENCES dbo.Users(Id)
	);