CREATE TABLE NotificationReviews (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Message NVARCHAR(255),
    UserId UNIQUEIDENTIFIER NOT NULL,
	EmployeeId UNIQUEIDENTIFIER NOT NULL,
	PaymentId UNIQUEIDENTIFIER NOT NULL,
    CreatedAt DATETIME,
    Sent BIT DEFAULT 0,
	FOREIGN KEY (UserId) REFERENCES Users(Id),
	FOREIGN KEY (EmployeeId) REFERENCES Users(Id),
	FOREIGN KEY (PaymentId) REFERENCES UserPayment(Id)
);